export const VEHICLE_OPTIONS = [
  'Audi A1',
  'Audi A3 Sedan',
  'Audi A4',
  'Audi Q3',
  'Audi Q5',
  'BMW 118i',
  'BMW 320i',
  'BMW X1',
  'BMW X3',
  'BYD Dolphin',
  'BYD Dolphin Mini',
  'BYD King',
  'BYD Seal',
  'BYD Song Plus',
  'BYD Yuan Pro',
  'CAOA Chery Arrizo 6',
  'CAOA Chery iCar',
  'CAOA Chery Tiggo 5X',
  'CAOA Chery Tiggo 7',
  'CAOA Chery Tiggo 8',
  'Chevrolet Agile',
  'Chevrolet Blazer',
  'Chevrolet Celta',
  'Chevrolet Classic',
  'Chevrolet Cobalt',
  'Chevrolet Cruze',
  'Chevrolet Equinox',
  'Chevrolet Joy',
  'Chevrolet Montana',
  'Chevrolet Onix',
  'Chevrolet Onix Plus',
  'Chevrolet Prisma',
  'Chevrolet S10',
  'Chevrolet Spin',
  'Chevrolet Tracker',
  'Chevrolet Trailblazer',
  'Citroen Aircross',
  'Citroen Basalt',
  'Citroen C3',
  'Citroen C3 Aircross',
  'Citroen C4 Cactus',
  'Fiat Argo',
  'Fiat Bravo',
  'Fiat Cronos',
  'Fiat Fastback',
  'Fiat Fiorino',
  'Fiat Freemont',
  'Fiat Grand Siena',
  'Fiat Idea',
  'Fiat Linea',
  'Fiat Mobi',
  'Fiat Palio',
  'Fiat Pulse',
  'Fiat Siena',
  'Fiat Strada',
  'Fiat Toro',
  'Fiat Uno',
  'Ford Ecosport',
  'Ford Edge',
  'Ford Fiesta',
  'Ford Focus',
  'Ford Fusion',
  'Ford Ka',
  'Ford Ranger',
  'GWM Haval H6',
  'GWM Ora 03',
  'Honda Accord',
  'Honda City',
  'Honda Civic',
  'Honda CR-V',
  'Honda Fit',
  'Honda HR-V',
  'Honda WR-V',
  'Hyundai Creta',
  'Hyundai HB20',
  'Hyundai HB20S',
  'Hyundai ix35',
  'Hyundai Santa Fe',
  'Hyundai Tucson',
  'Hyundai Veloster',
  'Jeep Commander',
  'Jeep Compass',
  'Jeep Renegade',
  'Jeep Wrangler',
  'Kia Cerato',
  'Kia Niro',
  'Kia Picanto',
  'Kia Seltos',
  'Land Rover Discovery Sport',
  'Land Rover Evoque',
  'Mercedes-Benz C180',
  'Mercedes-Benz GLA 200',
  'Mercedes-Benz GLB 200',
  'Mercedes-Benz Sprinter',
  'Mitsubishi ASX',
  'Mitsubishi Eclipse Cross',
  'Mitsubishi L200',
  'Mitsubishi Outlander',
  'Nissan Frontier',
  'Nissan Kicks',
  'Nissan March',
  'Nissan Sentra',
  'Nissan Versa',
  'Peugeot 2008',
  'Peugeot 208',
  'Peugeot 3008',
  'Peugeot Partner',
  'Porsche Cayenne',
  'Porsche Macan',
  'RAM 1500',
  'RAM Rampage',
  'Renault Captur',
  'Renault Duster',
  'Renault Kardian',
  'Renault Kwid',
  'Renault Logan',
  'Renault Master',
  'Renault Oroch',
  'Renault Sandero',
  'Renault Stepway',
  'Renault Symbol',
  'Toyota Corolla',
  'Toyota Corolla Cross',
  'Toyota Etios',
  'Toyota Hilux',
  'Toyota RAV4',
  'Toyota SW4',
  'Volkswagen Amarok',
  'Volkswagen Fox',
  'Volkswagen Fusca',
  'Volkswagen Gol',
  'Volkswagen Jetta',
  'Volkswagen Nivus',
  'Volkswagen Passat',
  'Volkswagen Polo',
  'Volkswagen Saveiro',
  'Volkswagen T-Cross',
  'Volkswagen Taos',
  'Volkswagen Tiguan',
  'Volkswagen Touareg',
  'Volkswagen Up',
  'Volkswagen Virtus',
  'Volkswagen Voyage',
  'Volvo C40',
  'Volvo EX30',
  'Volvo XC40',
  'Volvo XC60'
];
